// Package flint provides AST-based validation of Go source code that
// uses the fluent HTML framework. It catches common misuse patterns
// that defeat JIT optimisation or introduce security vulnerabilities.
//
// The linter operates on source code strings using go/parser and
// go/ast. It has no dependency on fluent itself.
package flint

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"sort"
)

// Diagnostic reports a single problem found in the source code.
type Diagnostic struct {
	Pos     token.Position
	End     token.Position
	Message string
	Fix     string
}

// checkFunc is the signature for individual lint checks.
type checkFunc func(fset *token.FileSet, file *ast.File) []Diagnostic

// activeRegistry holds the registry used by symbol validation checks.
var activeRegistry *Registry

// checks is the list of all lint checks that Source runs.
var checks = []checkFunc{
	checkStatic,
	checkRawText,
	checkImports,
	checkSetAttrChain,
	checkSetAttrKey,
	checkTypedParams,
	checkConstructors,
	checkSymbols,
	checkArity,
}

// WithRegistry sets the registry used for symbol validation. Call this
// once at initialisation with a registry generated by fluent-gen.
// Passing nil disables symbol checking.
func WithRegistry(r *Registry) {
	activeRegistry = r
}

// Source analyses Go source code and returns all diagnostics found.
// The filename is used only for position information in diagnostics.
//
// An error is returned only if the source cannot be parsed. Lint
// diagnostics are returned in the slice, not as errors.
func Source(filename string, src []byte) ([]Diagnostic, error) {
	if bytes.Contains(src, []byte("// Code generated")) && bytes.Contains(src, []byte("DO NOT EDIT")) {
		return nil, nil
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.AllErrors)
	if err != nil {
		return nil, err
	}

	var diags []Diagnostic
	for _, check := range checks {
		diags = append(diags, check(fset, file)...)
	}

	sort.Slice(diags, func(i, j int) bool {
		if diags[i].Pos.Line != diags[j].Pos.Line {
			return diags[i].Pos.Line < diags[j].Pos.Line
		}
		return diags[i].Pos.Column < diags[j].Pos.Column
	})

	return diags, nil
}
