package flint

import "testing"

func TestGeneratedFileSkip(t *testing.T) {
	l := New(FluentRegistry())

	t.Run("marker before the package clause skips the file", func(t *testing.T) {
		src := `// Code generated by fluent-generator. DO NOT EDIT.

package p

import "github.com/jpl-au/fluent/html5/div"

func f() {
	div.New().Fragment()
}`
		diags, err := l.Source("gen.go", []byte(src))
		if err != nil {
			t.Fatalf("unexpected parse error: %v", err)
		}
		if len(diags) != 0 {
			t.Errorf("generated file should be skipped, got %d diagnostics", len(diags))
		}
	})

	t.Run("marker text in a string literal does not skip the file", func(t *testing.T) {
		src := `package p

import "github.com/jpl-au/fluent/html5/div"

const banner = "// Code generated by tooling. DO NOT EDIT."

func f() {
	div.New().Fragment()
}`
		diags, err := l.Source("notgen.go", []byte(src))
		if err != nil {
			t.Fatalf("unexpected parse error: %v", err)
		}
		if len(diags) == 0 {
			t.Error("file mentioning the marker in a literal should still be linted")
		}
	})
}
