// Package lint provides AST-based validation of Go source code that uses
// the fluent HTML framework. It catches common misuse patterns that defeat
// JIT optimisation or introduce security vulnerabilities.
//
// The linter operates on source code strings using go/parser and go/ast.
// It has no dependency on fluent itself.
package flint

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"sort"
)

// Diagnostic reports a single problem found in the source code.
type Diagnostic struct {
	Pos     token.Position // file, line, column of the problematic expression
	End     token.Position // end of the problematic expression
	Message string         // human-readable description of the problem
	Fix     string         // suggested replacement or action
}

// checkFunc is the signature for individual lint checks. Each check walks
// the AST and appends any diagnostics it finds.
type checkFunc func(fset *token.FileSet, file *ast.File) []Diagnostic

// activeRegistry holds the registry used by symbol validation checks.
// Set via WithRegistry before calling Source.
var activeRegistry *Registry

// checks is the list of all lint checks that Source runs.
var checks = []checkFunc{
	checkStaticLiteral,
	checkRawTextLiteral,
	checkReservedImports,
	checkSetAttributeChain,
	checkSetAttributeKey,
	checkTypedParams,
	checkConstructorUsage,
	checkSymbols,
	checkArity,
}

// WithRegistry sets the registry used for symbol validation. When set,
// Source will verify that all package-level function calls and method
// chains reference symbols that exist in the registered API surface.
//
// Call this once at initialisation with a registry generated by
// fluent-gen. Passing nil disables symbol checking.
func WithRegistry(r *Registry) {
	activeRegistry = r
}

// Source analyses Go source code and returns all diagnostics found.
// The filename parameter is used only for position information in
// diagnostics; it does not need to refer to a real file.
//
// An error is returned only if the source cannot be parsed. Lint
// diagnostics are returned in the slice, not as errors.
func Source(filename string, src []byte) ([]Diagnostic, error) {
	// Skip generated files following the Go convention:
	// https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
	if bytes.Contains(src, []byte("// Code generated")) && bytes.Contains(src, []byte("DO NOT EDIT")) {
		return nil, nil
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.AllErrors)
	if err != nil {
		return nil, err
	}

	var diags []Diagnostic
	for _, check := range checks {
		diags = append(diags, check(fset, file)...)
	}

	// Sort by source position so consumers see diagnostics in file order.
	sort.Slice(diags, func(i, j int) bool {
		if diags[i].Pos.Line != diags[j].Pos.Line {
			return diags[i].Pos.Line < diags[j].Pos.Line
		}
		return diags[i].Pos.Column < diags[j].Pos.Column
	})

	return diags, nil
}
