package flint

// Registry describes the public API surface of a set of packages.
// The linter uses it to verify that source code references valid
// symbols. The registry is generated by fluent-gen from the same
// YAML specifications that produce the element packages.
type Registry struct {
	// Packages maps import paths to their exported API surface.
	// For example: "github.com/jpl-au/fluent/html5/div" -> Package{...}
	Packages map[string]Package
}

// Package describes the exported symbols of a single Go package.
type Package struct {
	// Functions maps package-level exported function names to their
	// expected argument count. A value of -1 indicates a variadic
	// function that accepts any number of arguments. The linter uses
	// this to validate both symbol existence and call arity.
	Functions map[string]int

	// Methods lists methods available on the package's primary type.
	// For element packages this is the element type (Class, ID, Name, etc.).
	// Nil for packages that have no primary type (node, text).
	Methods map[string]bool

	// Types lists exported type names (interfaces, structs, type aliases).
	// For the node package these are Node, Element, Dynamic, etc. For
	// element packages this is Element. The symbol checker uses this to
	// avoid false positives on type references in signatures and
	// assertions.
	Types map[string]bool

	// Vars lists package-level exported variables by name.
	// For enum packages these are the predefined values (Text, Email, etc.).
	Vars map[string]bool

	// TypedParams maps method names to their expected enum package name.
	// For example: "Type" -> "inputtype" means .Type() expects an
	// inputtype.InputType value, not a string literal. Only methods
	// that accept typed enum parameters are listed.
	TypedParams map[string]string

	// AttrMethods maps lowercase HTML attribute names to the fluent
	// method that manages them. For example: "class" -> "Class",
	// "href" -> "Href". Used to detect SetAttribute calls that should
	// use the dedicated typed method instead.
	AttrMethods map[string]string

	// TypedConstructors maps constructor names to the child package
	// they accept. For example: "Items" -> "li" means Items() accepts
	// ...*li.Element. Used to suggest typed constructors when New() is
	// called with children that all come from a single child package.
	TypedConstructors map[string]string
}

// ReservedAliases maps Go reserved keyword package names to their
// correct fluent package alternatives. These are checked at the
// import level, not per-package.
var ReservedAliases = map[string]string{
	"select": "dropdown",
	"main":   "primary",
	"var":    "variable",
}
