package flint

import "strings"

// Registry describes the public API surface of a set of packages.
// The linter uses it to verify that source code references valid
// symbols. The registry is generated by fluent-generator from the same
// YAML specifications that produce the element packages.
type Registry struct {
	// Packages maps import paths to their exported API surface.
	// For example: "github.com/jpl-au/fluent/html5/div" -> Package{...}
	Packages map[string]Package
}

// Package describes the exported symbols of a Go package. For the common case
// of one element per package it describes that element directly. For a
// multi-element package (the svg package, whose single import path hosts many
// element types) the fields describe the shared surface - Functions lists
// every constructor, Methods the methods common to every element, and
// FuncReturns/TypeMethods resolve each constructor's element type for
// chained-method validation - while Elements describes each element for
// `flint -info`.
type Package struct {
	// Tag is the HTML tag an element package renders, e.g. "div" for
	// the div package or "select" for the dropdown package. It differs
	// from the package name only where the tag is a Go keyword
	// (select, main, var, map). Empty for non-element packages.
	Tag string

	// Functions maps package-level exported function names to their
	// expected argument count. A value of -1 indicates a variadic
	// function that accepts any number of arguments. The linter uses
	// this to validate both symbol existence and call arity.
	Functions map[string]int

	// Methods maps the methods available on the package's primary type to
	// their expected argument count, with -1 for variadic (the Functions
	// convention). For element packages this is the element type (Class, ID,
	// Name, etc.). Nil for packages that have no primary type (node, text).
	Methods map[string]int

	// Types lists exported type names (interfaces, structs, type aliases).
	// For the node package these are Node, Element, Dynamic, etc. For
	// element packages this is Element. The symbol checker uses this to
	// avoid false positives on type references in signatures and
	// assertions.
	Types map[string]bool

	// Vars lists package-level exported variables by name.
	// For enum packages these are the predefined values (Text, Email, etc.).
	Vars map[string]bool

	// DeprecatedFunctions maps a deprecated package-level function to its
	// deprecation note, e.g. "Flash" -> "Flash is no longer supported by
	// browsers." for the embed package. The note names the replacement, so
	// diagnostics carry it as the fix. Every name here also appears in
	// Functions: deprecated symbols still exist and compile.
	DeprecatedFunctions map[string]string

	// DeprecatedMethods maps a deprecated element method to its deprecation
	// note, e.g. "Border" -> "Use CSS border properties instead." for the
	// table package. Every name here also appears in Methods.
	DeprecatedMethods map[string]string

	// DeprecatedVars maps a deprecated package-level var to its deprecation
	// note. For enum packages these are withdrawn options, e.g. the inputtype
	// option "Datetime". Every name here also appears in Vars.
	DeprecatedVars map[string]string

	// EnumValues maps a rendered HTML value to the Go constant that produces
	// it, e.g. "email" -> "Email" for the inputtype package. Populated only
	// for enum packages. The typed-params check uses it to name the exact
	// constant a raw string should become.
	EnumValues map[string]string

	// TypedParams maps method names to their expected enum package name.
	// For example: "Type" -> "inputtype" means .Type() expects an
	// inputtype.InputType value, not a string literal. Only methods
	// that accept typed enum parameters are listed.
	TypedParams map[string]string

	// AttrMethods maps lowercase HTML attribute names to the fluent
	// method that manages them. For example: "class" -> "Class",
	// "href" -> "Href". Used to detect SetAttribute calls that should
	// use the dedicated typed method instead.
	AttrMethods map[string]string

	// AccumulatingMethods lists the attribute methods whose repeated calls
	// concatenate values rather than overwrite them (Class joins with a
	// space, Style with a semicolon). The duplicate-attr check exempts
	// them: calling one twice in a chain is legitimate.
	AccumulatingMethods map[string]bool

	// URLFunctions maps a package-level function to the index of its URL
	// parameter, whose value the runtime passes through fluent's scheme
	// filter (node.FilterURL): http, https, mailto, tel, sms and relative
	// URLs survive; anything else renders as the #fluent-unsafe-url
	// sentinel. For example embed.Flash's src is index 0.
	URLFunctions map[string]int

	// URLMethods is URLFunctions for the element's methods, e.g.
	// "Href" -> 0 on the a element.
	URLMethods map[string]int

	// TypedConstructors maps constructor names to the child package
	// they accept. For example: "Items" -> "li" means Items() accepts
	// ...*li.Element. Used to suggest typed constructors when New() is
	// called with children that all come from a single child package.
	TypedConstructors map[string]string

	// Constructors describes what each package-level constructor does for you,
	// in terms of the chained calls it makes unnecessary. It is what lets the
	// constructor check see past the method name: a
	// link.New().Rel(rel.Stylesheet).Href(u) chain names no constructor at all,
	// yet what it sets identifies link.Stylesheet exactly. Only constructors a
	// chain could be rewritten to appear - New is absent, as are the ones that
	// derive a value no chain of setters produces (area.Rect builds its coords
	// with fmt.Sprintf), so Functions remains the full list.
	Constructors map[string]Constructor

	// FuncReturns maps a package function to the type it returns, when that
	// type is not the package's own element. Values are import-path-qualified
	// type names (e.g. "github.com/jpl-au/fluent/node.Node"). The chained-method
	// check follows this to validate a method against the function's real return
	// type instead of assuming the package element - so security.PlainText(...).
	// Render() resolves against node.Node (which has Render) rather than the
	// security Cleaner (which does not). Functions absent from the map are not
	// assumed to return anything in particular.
	FuncReturns map[string]string

	// TypeMethods lists the method set of a named exported type, keyed by the
	// bare type name, with each method mapped to its argument count (-1
	// variadic). It is populated only for types that FuncReturns points at,
	// so the chained-method check can resolve them. For the node package:
	// "Node" -> {Render: 1, WriteTo: 1, RenderBytes: 0, RenderBuilder: 1, Nodes: 0}.
	TypeMethods map[string]map[string]int

	// Elements describes the individual elements of a multi-element package,
	// keyed by HTML tag (e.g. "rect" for the svg package, whose single import
	// path hosts many element types). It is nil for the common case of one
	// element per package, where the fields above already describe that element.
	// flint -info uses it to resolve and present a specific element within the
	// package.
	Elements map[string]Package
}

// Constructor describes one package-level constructor by the chained calls it
// replaces, so the constructor check can recognise a New() chain doing the same
// work by hand.
type Constructor struct {
	// Sets lists the element methods the constructor applies for you, sorted.
	// For link.Stylesheet these are Href and Rel; for a.Link, Href and Text.
	Sets []string

	// Pins maps a method in Sets to the value the constructor fixes it to,
	// written as it appears in Go source: "Rel" -> "rel.Stylesheet" for
	// link.Stylesheet, "Type" -> `"module"` for script.Module. It is what tells
	// otherwise identical constructors apart. Methods absent from the map take
	// whatever the caller passes.
	Pins map[string]string

	// Prefixes maps a method in Sets to the literal the constructor puts in
	// front of its argument, e.g. "Href" -> "mailto:" for a.MailTo. It
	// distinguishes the scheme-pinned anchor constructors from a.Link, which
	// passes the href through untouched.
	Prefixes map[string]string

	// Content lists the methods in Sets that add child nodes rather than set an
	// attribute (Text, RawText, Static, Textf, RawTextf).
	Content []string

	// Nodes reports whether the constructor ends in a ...node.Node parameter,
	// so a New(children...) chain can still collapse into it.
	Nodes bool
}

// typeMethods returns the method set of a path-qualified type, for example
// "github.com/jpl-au/fluent/node.Node", or nil when the type or its methods are
// not recorded. The qualifier splits at the final dot: a Go type name never
// contains one, so everything before it is the import path.
func (r *Registry) typeMethods(qualified string) map[string]int {
	i := strings.LastIndex(qualified, ".")
	if i < 0 {
		return nil
	}
	return r.Packages[qualified[:i]].TypeMethods[qualified[i+1:]]
}

// elementOfFunc returns the element of a multi-element package that fn
// constructs, found by the constructor recorded on each element. ok is false
// for a single-element package, whose own fields already describe it, and for
// a function no element claims.
func elementOfFunc(pkg Package, fn string) (Package, bool) {
	for _, el := range pkg.Elements {
		if _, ok := el.Functions[fn]; ok {
			return el, true
		}
	}
	return Package{}, false
}

// TagAliases returns a map from HTML tag to fluent package name for
// element packages whose name differs from the tag they render. These
// are tags that collide with Go keywords: select, main, var, and map
// become dropdown, primary, variable, and imagemap.
func (r *Registry) TagAliases() map[string]string {
	aliases := make(map[string]string)
	for path, pkg := range r.Packages {
		if name := lastSegment(path); pkg.Tag != "" && pkg.Tag != name {
			aliases[pkg.Tag] = name
		}
	}
	return aliases
}
